### ISSUE TITLE
EntityCollectionHtmlRouteProvider.php

### ISSUE THREAD

**Issue by efpapado** [esolitos/entity_collection#6]
Why did you implement the routing into a class (EntityCollectionHtmlRouteProvider) and not into a entity_collection.routing.yml file?

**Comment by esolitos** [comment]
Because in that way we can [have dynamic routes, see this documentation](https://www.drupal.org/docs/8/api/routing-system/providing-dynamic-routes).
This is useful since in my mind each "AdminUI" plugin can define its own route.
